CREATE TABLE a1 (
  id int NOT NULL,
  val int DEFAULT NULL,
  PRIMARY KEY (id) 
) ENGINE=InnoDB;


CREATE TABLE a2 (
  id int NOT NULL,
  val char(3) DEFAULT NULL,
  FOREIGN KEY (id) REFERENCES a (id) 
) ENGINE=InnoDB;


CREATE TABLE a3 (
  id int DEFAULT NULL,
  val int DEFAULT NULL,
  FOREIGN KEY (id) REFERENCES a (id) 
) ENGINE=InnoDB;