CREATE TABLE b1 (
  id int NOT NULL,
  val int DEFAULT NULL,
  PRIMARY KEY (id) 
) ENGINE=InnoDB;


CREATE TABLE b2 (
  id int NOT NULL,
  val char(3) DEFAULT NULL,
  FOREIGN KEY (id) REFERENCES a (id) 
) ENGINE=InnoDB;


CREATE TABLE b3 (
  id int DEFAULT NULL,
  val int DEFAULT NULL,
  FOREIGN KEY (id) REFERENCES a (id) 
) ENGINE=InnoDB;